# Generated by Django 2.1.5 on 2019-02-07 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Yelp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='origin',
            new_name='summary',
        ),
        migrations.RemoveField(
            model_name='food',
            name='submission_date',
        ),
    ]
